import type { UIState } from "./useStore";

type S = UIState;

export const selInputText = (s: S) => s.inputText;
export const selSetInputText = (s: S) => s.setInputText;
export const selSendMessage = (s: S) => s.sendMessage;
export const selIsStreaming = (s: S) => s.isStreaming;
export const selIsCommandMenuOpen = (s: S) => s.isCommandMenuOpen;
export const selSetCommandMenuOpen = (s: S) => s.setCommandMenuOpen;
export const selCancelPrompt = (s: S) => s.cancelPrompt;
export const selEscCancelTimer = (s: S) => s.escCancelTimer;
export const selSetEscCancelTimer = (s: S) => s.setEscCancelTimer;
export const selQueuedPrompts = (s: S) => s.queuedPrompts;
export const selSendQueuedPromptNow = (s: S) => s.sendQueuedPromptNow;
export const selActiveSession = (s: S) => s.activeSession;
export const selConnectionError = (s: S) => s.connectionError;
export const selReconnectFailed = (s: S) => s.reconnectFailed;
export const selReconnectAgent = (s: S) => s.reconnectAgent;
export const selSlashCommands = (s: S) => s.slashCommands;
export const selAgentRoles = (s: S) => s.agentRoles;
export const selMentionMenuOpen = (s: S) => s.mentionMenuOpen;
export const selSetMentionMenuOpen = (s: S) => s.setMentionMenuOpen;
export const selOpenCommandPopup = (s: S) => s.openCommandPopup;
export const selRemoveQueuedPrompt = (s: S) => s.removeQueuedPrompt;
export const selPastedSnippets = (s: S) => s.pastedSnippets;
export const selRemovePastedSnippet = (s: S) => s.removePastedSnippet;
export const selActiveAgent = (s: S) => s.activeAgent;
export const selAgents = (s: S) => s.agents;
export const selAttachments = (s: S) => s.attachments;
export const selRemoveAttachment = (s: S) => s.removeAttachment;
export const selSetConfig = (s: S) => s.setConfig;
export const selConfigOptions = (s: S) => s.configOptions;
export const selSelectAgent = (s: S) => s.selectAgent;
export const selCommandPopup = (s: S) => s.commandPopup;
export const selCloseCommandPopup = (s: S) => s.closeCommandPopup;
export const selOpenSessionMenu = (s: S) => s.openSessionMenu;
export const selMessages = (s: S) => s.messages;
export const selActiveRole = (s: S) => s.activeRole;
export const selSwitchRole = (s: S) => s.switchRole;
export const selSessions = (s: S) => s.sessions;
export const selSwitchSession = (s: S) => s.switchSession;
export const selDeleteSession = (s: S) => s.deleteSession;
export const selClearEmptySessions = (s: S) => s.clearEmptySessions;
export const selNewSession = (s: S) => s.newSession;
export const selSessionMenuOpen = (s: S) => s.sessionMenuOpen;
export const selCloseSessionMenu = (s: S) => s.closeSessionMenu;
export const selLocale = (s: S) => s.locale;
